### ISSUE TITLE
UI打不開

### ISSUE THREAD

**Issue by 777oxxo** [Eugeoter/waifuset#3]
PS D:\waifuset> python api.py --source G:\v\modujinbin\0315\1 --write_to_txt --language cn
[ERROR] failed to load priority config:
[ui_dataset] overload: ['G:\\v\\modujinbin\\0315\\1'] -> None
reading `1`: 100%|████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<?, ?steps/s]
initializing buffer:   0%|                                                                    | 0/2 [00:00<?, ?steps/s]
Traceback (most recent call last):
  File "D:\waifuset\api.py", line 16, in <module>
    api(args)
  File "D:\waifuset\api.py", line 7, in api
    ui: gr.Blocks = create_ui(args)
  File "D:\waifuset\waifuset\ui\ui.py", line 184, in create_ui
    univset, buffer, sample_history, tag_priority_manager, subset, waifu_tagger, waifu_scorer, tag_table, tag_feature_table = init_everything()
  File "D:\waifuset\waifuset\ui\ui.py", line 172, in init_everything
    main_dataset = prepare_dataset(univargs)
  File "D:\waifuset\waifuset\ui\ui.py", line 86, in prepare_dataset
    dataset = UIDataset(
  File "D:\waifuset\waifuset\ui\ui_dataset.py", line 342, in __init__
    if img_key not in database:
TypeError: argument of type 'NoneType' is not iterable

**Comment by Eugeoter** [comment]
Fixed. Sorry for the inconvenience.
