### ISSUE TITLE
奇怪的报错

### ISSUE THREAD

**Issue by 1zhangyy1** [Eugeoter/waifuset#5]
佬，这个每次打开会报下错，重装一次又会好

tag table not found in root: /root/sd-dataset-manager/waifuset/waifuset
[ui_dataset] synchronous txts R/W
[ui_dataset] reading `biaoqing`: 100%|█████| 486/486 [00:00<00:00, 87388.83it/s]
[ui_dataset] info: total=181 | buffer=115 | categories=3
Traceback (most recent call last):
  File "/root/sd-dataset-manager/waifuset/api.py", line 16, in <module>
    api(args)
  File "/root/sd-dataset-manager/waifuset/api.py", line 7, in api
    ui: gr.Blocks = create_ui(args)
  File "/root/sd-dataset-manager/waifuset/waifuset/ui/ui.py", line 253, in create_ui
    query_include_tags = gr.Dropdown(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/components/dropdown.py", line 101, in __init__
    raise ValueError(
ValueError: Custom values are not supported when `multiselect` is True.

**Comment by Eugeoter** [comment]
您需要安装项目指定的gradio版本：
```bash
pip install gradio==4.13.0
```

**Comment by 1zhangyy1** [comment]
谢谢佬，这个打标器超好用
